# name: Terraform Pipeline

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:

# jobs:
#   terraform:
#     runs-on: ubuntu-20.04

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v1

#       - name: Terraform Init
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         run: terraform init

#       - name: Terraform Plan
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         run: terraform plan

#       - name: Terraform Apply
#         id: generate_token
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         run: terraform apply -auto-approve
      
#       - name: Wait for approval to Destroy
#         uses: trstringer/manual-approval@v1
#         with:
#           secret: ${{ github.TOKEN }}
#           approvers: alionur07
#           minimum-approvals: 1

#       - name: Terraform Destroy
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         run: terraform destroy -auto-approve

# #test